server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: authenticationService
        uri: http://localhost:8082/
        predicates:
        - Path=/users/**
      - id: productService
        uri: http://localhost:8081/
        predicates:
        - Path=/products/**
logging:
  level:
    org.springframework.web: DEBUG
